### ISSUE TITLE
prokka data

### ISSUE THREAD

**Issue by abrozzi** [MicrobiologyETHZ/NCCR_genomicsPipeline#5]
Hi,

I read your paper https://pubmed.ncbi.nlm.nih.gov/31633483/ and wanted to now if the PROKKA sequences (PROKKA_00001, PROKKA_00002,etc...) are available:
https://github.com/ASintsova/HUTI-RNAseq/blob/master/data/raw_counts/HM01_UR_counts.txt

Thank you very much,
-A

**Comment by ASintsova** [comment]
Thank you for your interest! You should receive an e-mail with a link to the sequences. I'll contact people still working on the project, and make sure these are publically available soon. Let me know if there's anything else you need.

Thanks,

Anna

**Comment by abrozzi** [comment]
Thank you very much: my mail is alessandro.brozzi@gmail.com
